version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_CUSTOM_EXTENSIONS=/data/custom
    volumes:
      - n8n_data:/home/node/.n8n
      - ./packages/n8n-nodes:/data/custom
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Demo contracts (for testing)
  contracts:
    build:
      context: ./packages/contracts
      dockerfile: Dockerfile
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CELOSCAN_API_KEY=${CELOSCAN_API_KEY}
    volumes:
      - ./packages/contracts:/app
    working_dir: /app

volumes:
  n8n_data:
  postgres_data:
  redis_data:
